CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=fe93c771-c349-492e-89ce-218f4eb6ffa9

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
